{
    "application": "{{ var "applicationName" }}",
    "name": "{{ var "pipelineName" }}",
    "description": "{{ var "pipelineDescription" ?: "" }}",
    "appConfig": {},
    "keepWaitingPipelines": false,
    "limitConcurrent": true,
    "schema": "1",
    "spelEvaluator": "v4",
    "stages": [
        {
        "action": "plan",
        "artifacts": [
            {
            "account": "gitrepo",
            "artifact": {
                "artifactAccount": "gitrepo",
                "id": "5a611316-41ff-46a6-8624-4c08e0470973",
                "reference": "https://github.com/minhthong582000/arm.git",
                "type": "git/repo",
                "version": "main"
            }
            }
        ],
        "dir": "deploy/terraform",
        "expectedArtifacts": [
            {
            "defaultArtifact": {
                "customKind": true,
                "id": "b4ea4576-b58a-4e83-8856-a545ee8b6cf7"
            },
            "displayName": "planfile",
            "id": "69af1006-0536-4f57-98ee-6a820c88aaf3",
            "matchArtifact": {
                "artifactAccount": "embedded-artifact",
                "id": "8f98f099-8136-4645-a37a-0529c4d68958",
                "name": "planfile",
                "type": "embedded/base64"
            },
            "useDefaultArtifact": false,
            "usePriorArtifact": false
            }
        ],
        "name": "Plan",
        "overrides": {},
        "profile": "",
        "refId": "1",
        "requisiteStageRefIds": [],
        "targets": [],
        "terraformVersion": "1.0.9",
        "type": "terraform"
        },
        {
        "failPipeline": true,
        "judgmentInputs": [],
        "name": "Manual Judgment",
        "notifications": [],
        "refId": "2",
        "requisiteStageRefIds": [
            "1"
        ],
        "type": "manualJudgment"
        },
        {
        "action": "apply",
        "artifacts": [
            {
            "account": "gitrepo",
            "artifact": {
                "artifactAccount": "gitrepo",
                "id": "01ffe0d4-1261-4a56-b156-0e1ae23645a9",
                "reference": "https://github.com/minhthong582000/arm.git",
                "type": "git/repo",
                "version": "main"
            }
            },
            {
            "account": "",
            "id": "69af1006-0536-4f57-98ee-6a820c88aaf3"
            }
        ],
        "dir": "deploy/terraform",
        "name": "Apply",
        "overrides": {},
        "refId": "3",
        "requisiteStageRefIds": [
            "2"
        ],
        "terraformVersion": "1.0.9",
        "type": "terraform"
        },
        {
        "action": "output",
        "artifacts": [
            {
            "account": "gitrepo",
            "artifact": {
                "artifactAccount": "gitrepo",
                "id": "3892a231-2d89-474c-b17e-b6101da271f5",
                "reference": "https://github.com/minhthong582000/arm.git",
                "type": "git/repo",
                "version": "main"
            }
            }
        ],
        "dir": "deploy/terraform",
        "name": "Output",
        "overrides": {},
        "refId": "4",
        "requisiteStageRefIds": [
            "3"
        ],
        "terraformVersion": "1.0.9",
        "type": "terraform"
        }
    ],
    "triggers": [
        {
        "branch": "main",
        "enabled": true,
        "project": "minhthong582000",
        "secret": "34af7b9d3596ba821ba02ae558f5b5ef9a5340aa",
        "slug": "arm",
        "source": "github",
        "type": "git"
        }
    ]
}