{
  "action": "{{ var "action" }}",
  "refId": "{{ var "refId" }}",
  "requisiteStageRefIds": {{ var "requisiteStageRefIds" ?: [] }},
  "artifacts": {{ var "artifacts" }},
  "backendArtifact": {{ var "backendArtifact" ?: {} }},
  "dir": "{{ var "dir" }}",
  "expectedArtifacts": {{ var "expectedArtifacts" ?: [] }},
  "name": "{{ var "name" ?: "Terraform" }}",
  "overrides": {{ var "overrides" ?: {} }},
  "terraformVersion": "{{ var "terraformVersion" ?: "0.13.6" }}",
  "profile": "{{ var "profile" ?: "" }}",
  "type": "terraform",
  "sendNotifications": true,
  "notifications": {{ var "notifications" ?: [] }}
}